version: "3.3"

services:
  microservicecicd-send:
    image: udemy-microservicecicd-send:v1
    ports:
      - 8080:8080
    environment:
      - spring.boot.admin.client.url=${SPRING_ADMIN}
    networks:
      - udemy

networks:
  udemy:
    external: true